/**
 * Subset of AgentRegistry ABI consumed by the dApp.
 * Generated by hand to keep the bundle small — the full ABI lives in
 * out/AgentRegistry.sol/AgentRegistry.json after `forge build`.
 */
export const agentRegistryAbi = [
    {
        type: "function",
        name: "nextAgentId",
        inputs: [],
        outputs: [{ type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getAgent",
        inputs: [{ name: "agentId", type: "uint256" }],
        outputs: [
            {
                type: "tuple",
                components: [
                    { name: "owner", type: "address" },
                    { name: "signer", type: "address" },
                    { name: "stake", type: "uint256" },
                    { name: "pricePerJob", type: "uint256" },
                    { name: "maxResponseTime", type: "uint32" },
                    { name: "slashBps", type: "uint32" },
                    { name: "active", type: "bool" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "reputationScore",
        inputs: [{ name: "agentId", type: "uint256" }],
        outputs: [{ type: "uint8" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "completedJobs",
        inputs: [{ name: "agentId", type: "uint256" }],
        outputs: [{ type: "uint32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "slashedJobs",
        inputs: [{ name: "agentId", type: "uint256" }],
        outputs: [{ type: "uint32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getEndpoint",
        inputs: [{ name: "agentId", type: "uint256" }],
        outputs: [{ type: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "register",
        inputs: [
            { name: "signer", type: "address" },
            { name: "stakeAmount", type: "uint256" },
            { name: "pricePerJob", type: "uint256" },
            { name: "maxResponseTime", type: "uint32" },
            { name: "slashBps", type: "uint32" },
            { name: "endpoint", type: "string" },
        ],
        outputs: [{ type: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "AgentRegistered",
        inputs: [
            { name: "agentId", type: "uint256", indexed: true },
            { name: "owner", type: "address", indexed: true },
            { name: "signer", type: "address", indexed: false },
            { name: "stake", type: "uint256", indexed: false },
            { name: "pricePerJob", type: "uint256", indexed: false },
            { name: "maxResponseTime", type: "uint32", indexed: false },
            { name: "slashBps", type: "uint32", indexed: false },
            { name: "endpoint", type: "string", indexed: false },
        ],
    },
    {
        type: "event",
        name: "ReputationUpdated",
        inputs: [
            { name: "agentId", type: "uint256", indexed: true },
            { name: "completedJobs", type: "uint32", indexed: false },
            { name: "slashedJobs", type: "uint32", indexed: false },
        ],
    },
] as const;
